/**
 * Regression tests for the normalized recipe corpus + search data model
 * (WILS-3).
 *
 * Two layers:
 *   1. Corpus invariants over data/recipes.json — generated by `node build.js`
 *      from the Obsidian vault. The search index (stage 2) consumes this file,
 *      so it must stay free of parser/scrape debris.
 *   2. Unit tests for the normalization helpers exported by build.js so the
 *      extraction logic itself is pinned down, not just its output.
 */

const test = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..');
const build = require(path.join(ROOT, 'build.js'));

const read = (rel) => fs.readFileSync(path.join(ROOT, rel), 'utf8');

// Tokens that mark parser/scrape debris in meta values.
const META_DEBRIS = /cook time|method|yield|cuisine|category|stove|step\s*\d+|calories/i;
const DESC_DEBRIS = /cook mode|prevent your screen from going dark|jump to recipe/;
const INGR_DEBRIS = /cook mode|prevent your screen from going dark|^\d+\s*\/\s*\d+\s*$/;

// ── Corpus invariants ────────────────────────────────────

const corpus = JSON.parse(read('data/recipes.json'));

test('corpus is a non-empty array of 80+ normalized recipes', () => {
  assert.ok(Array.isArray(corpus), 'recipes.json must be an array');
  assert.ok(corpus.length >= 80, `expected a sizable corpus, got ${corpus.length}`);
});

test('every recipe carries the searchable schema fields', () => {
  for (const r of corpus) {
    assert.ok(r && typeof r === 'object', 'recipe must be an object');
    assert.match(r.id, /^[a-z0-9]+(-[a-z0-9]+)*$/, `slug id on: ${r.title}`);
    assert.ok(r.title, `title required on ${r.id}`);
    assert.ok(Array.isArray(r.description) ? true : typeof r.description === 'string', `description must be a string on ${r.id}`);
    assert.ok(Array.isArray(r.categories) && r.categories.length > 0, `categories on ${r.id}`);
    assert.ok(typeof r.description === 'string' || r.description === '', 'description type');
    assert.ok(Array.isArray(r.ingredients), `ingredients on ${r.id}`);
    assert.ok(typeof r.source === 'string' || r.source === null, `source on ${r.id}`);
    assert.ok(typeof r.dateAdded === 'string' && !Number.isNaN(new Date(r.dateAdded).getTime()), `dateAdded on ${r.id}`);
    assert.ok(r.content && typeof r.content === 'string', `content on ${r.id}`);
  }
});

test('no meta values leaked parser/scrape debris', () => {
  let checked = 0;
  for (const r of corpus) {
    for (const k of ['prepTime', 'cookTime', 'totalTime', 'servings']) {
      const v = r.meta[k];
      if (v) {
        checked++;
        assert.ok(!META_DEBRIS.test(v), `meta.${k} debris on ${r.id}: ${JSON.stringify(v)}`);
        assert.ok(!v.includes('**'), `meta.${k} bold markers on ${r.id}`);
      }
    }
  }
  assert.ok(checked > 0, 'expected at least some meta values to check');
});

test('numeric meta facets exist wherever the text has a number', () => {
  for (const r of corpus) {
    for (const k of ['prepTime', 'cookTime', 'totalTime']) {
      const t = r.meta[k];
      const minutes = r.meta[k + 'Minutes'];
      if (t && /\d/.test(t)) {
        assert.ok(Number.isInteger(minutes) && minutes >= 0, `meta.${k}Minutes must parse on ${r.id} (${JSON.stringify(t)})`);
      }
    }
    if (r.meta.servings && /\d/.test(r.meta.servings)) {
      assert.ok(Number.isInteger(r.meta.servingsMin), `servingsMin missing on ${r.id}`);
      assert.ok(Number.isInteger(r.meta.servingsMax), `servingsMax missing on ${r.id}`);
    }
  }
});

test('descriptions carry no markdown meta-block debris', () => {
  for (const r of corpus) {
    if (!r.description) continue;
    assert.ok(!r.description.trim().startsWith('- **'), `description starts with "- **" on ${r.id}`);
    assert.ok(!DESC_DEBRIS.test(r.description), `description boilerplate on ${r.id}`);
    assert.ok(r.description.length <= 300, `description too long on ${r.id}`);
  }
});

test('ingredients carry no ratings, cook-mode or title-echo junk', () => {
  for (const r of corpus) {
    for (const ing of r.ingredients) {
      assert.ok(!INGR_DEBRIS.test(ing), `ingredient junk on ${r.id}: ${JSON.stringify(ing)}`);
      assert.ok(!ing.includes('**'), `ingredient bold markers on ${r.id}`);
    }
  }
});

// ── Unit tests for build.js normalization ────────────────

test('cleanTitle unwraps fully-parenthesized titles only', () => {
  assert.strictEqual(build.cleanTitle('(Dolmas)'), 'Dolmas');
  assert.strictEqual(build.cleanTitle('Aloo Samosas (Potato Samosas) Recipe'), 'Aloo Samosas (Potato Samosas) Recipe');
  assert.strictEqual(build.cleanTitle('  Pork Chops  '), 'Pork Chops');
  assert.strictEqual(build.cleanTitle('**Soup**'), 'Soup');
});

test('cleanDuration strips flattening debris and yields minutes', () => {
  assert.deepStrictEqual(build.cleanDuration('45 mins Cook Time', 'prepTime'), { text: '45 mins', minutes: 45 });
  assert.deepStrictEqual(build.cleanDuration('6 Hr Serves', 'cookTime'), { text: '6 hrs', minutes: 360 });
  assert.deepStrictEqual(build.cleanDuration('1 hour 45 minutes Yield', 'totalTime'), { text: '1 hr 45 mins', minutes: 105 });
  assert.deepStrictEqual(build.cleanDuration('5 mins 10 mins 15 mins', 'totalTime'), { text: '15 mins', minutes: 15 });
  assert.deepStrictEqual(build.cleanDuration('2 days total', 'totalTime'), { text: '2 days', minutes: 2880 });
  assert.deepStrictEqual(build.cleanDuration('Overnight', 'prepTime'), { text: 'Overnight', minutes: null });
  assert.deepStrictEqual(build.cleanDuration(null, 'prepTime'), { text: null, minutes: null });
});

test('cleanServings strips scrape tails and derives min/max', () => {
  assert.deepStrictEqual(build.cleanServings('6 servings Step 1'), { text: '6 servings', min: 6, max: 6 });
  assert.deepStrictEqual(build.cleanServings('4 -6 SERVINGS 1X'), { text: '4 - 6 servings', min: 4, max: 6 });
  assert.deepStrictEqual(build.cleanServings('8people Calories'), { text: '8 people', min: 8, max: 8 });
  assert.deepStrictEqual(build.cleanServings('N'), { text: null, min: null, max: null });
  assert.deepStrictEqual(build.cleanServings('6 people'), { text: '6 people', min: 6, max: 6 });
  assert.deepStrictEqual(build.cleanServings(null), { text: null, min: null, max: null });
});

test('cleanDescription strips meta bullets and boilerplate', () => {
  const overview = [
    '- **Prep Time**: 45 mins Cook Time',
    '- **Cook Time**: 60 mins Method',
    '- **Total Time**: 1 hour 45 minutes Yield',
    '- **Servings**: 1',
  ].join('\n');
  assert.strictEqual(build.cleanDescription(overview, 'Dolmas'), '');
  assert.strictEqual(
    build.cleanDescription('A flexible, flavorful soup\nWorks on stovetop, slow cooker, or Instant Pot.', 'Black Bean Soup'),
    'A flexible, flavorful soup Works on stovetop, slow cooker, or Instant Pot.'
  );
});

test('isJunkIngredient flags ratings, cook-mode and title echo', () => {
  assert.ok(build.isJunkIngredient('Cook Mode Prevent your screen from going dark', 'Dolmas'));
  assert.ok(build.isJunkIngredient('1/5', 'Dolmas'));
  assert.ok(build.isJunkIngredient('BEST Stuffed Grape Leaves (Dolmas) - The Mediterranean Dish', 'Dolmas'));
  assert.ok(!build.isJunkIngredient('1/2 cup chopped onion', 'Soup'));
  assert.ok(!build.isJunkIngredient('2/3 cup warm water', 'Bread'));
});

function load(rel) {
  return JSON.parse(read(rel));
}